-- Temporarily disable RLS on CMS tables since auth is disabled

ALTER TABLE public.packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tours DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hotels DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_content DISABLE ROW LEVEL SECURITY;